require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CarrosController do
  it "deveria listar os carros no index" do
    carros_mock = [mock_model(Carro), mock_model(Carro)]

    Carro.should_receive(:all).and_return(carros_mock)

    get 'index'
    response.should be_success

    assigns[:carros].should == carros_mock
  end

  it "deveria instanciar um carro no index" do
    carro_mock = mock_model(Carro)

    Carro.should_receive(:new).and_return(carro_mock)

    get 'index'
    response.should be_success

    assigns[:carro].should == carro_mock
  end
end
